"""V3 finite-feedback pairwise-revision models for paper 1.

The module implements one micro mechanism and five deliberately nested
macroscopic descriptions:

* classical replicator;
* variance-only cubic tail;
* full moment cubic tail (including feedback skewness);
* exact finite-sample Fermi mean field;
* finite-population agent simulation.

Payoff feedback is generated by ``m`` i.i.d. opponent samples.  It is not an
externally fitted Gaussian perturbation.  This keeps every correction term
traceable to the payoff matrix, population state, and sample size.
"""

from __future__ import annotations

from functools import lru_cache
import math
from typing import Callable, Iterable

import numpy as np


Array = np.ndarray
 


KERNEL_COEFFICIENTS = {
    # q_beta(z) = z - c3 beta^2 z^3 + c5 beta^4 z^5 + O(beta^6)
    "fermi": (1.0 / 12.0, 1.0 / 120.0),
    "arctan": (1.0 / 3.0, 1.0 / 5.0),
}


def validate_state(x: Array, *, atol: float = 1e-10) -> Array:
    x = np.asarray(x, dtype=float)
    if x.ndim != 1 or x.size < 2:
        raise ValueError("x must be a one-dimensional probability vector")
    if not np.all(np.isfinite(x)) or np.min(x) < -atol:
        raise ValueError("x contains invalid probabilities")
    total = float(x.sum())
    if abs(total - 1.0) > atol:
        raise ValueError(f"x must sum to one; got {total}")
    return np.maximum(x, 0.0) / total


def validate_game(A: Array, k: int | None = None) -> Array:
    A = np.asarray(A, dtype=float)
    if A.ndim != 2 or A.shape[0] != A.shape[1]:
        raise ValueError("A must be a square payoff matrix")
    if k is not None and A.shape != (k, k):
        raise ValueError("payoff matrix and state dimension disagree")
    if not np.all(np.isfinite(A)):
        raise ValueError("A contains non-finite values")
    return A


def fermi(z: Array | float, beta: float) -> Array | float:
    """Numerically stable logistic comparison probability."""
    if beta <= 0 or not math.isfinite(beta):
        raise ValueError("beta must be positive and finite")
    a = np.asarray(z, dtype=float)
    out = np.empty_like(a)
    pos = a >= 0
    out[pos] = 1.0 / (1.0 + np.exp(-beta * a[pos]))
    ez = np.exp(beta * a[~pos])
    out[~pos] = ez / (1.0 + ez)
    return float(out) if out.ndim == 0 else out


def revision_probability(
    z: Array | float, beta: float, *, kernel: str = "fermi"
) -> Array | float:
    """Bounded pairwise adoption probability with matched slope convention."""
    if kernel == "fermi":
        return fermi(z, beta)
    if kernel != "arctan":
        raise ValueError(f"unknown revision kernel: {kernel}")
    if beta <= 0 or not math.isfinite(beta):
        raise ValueError("beta must be positive and finite")
    a = np.asarray(z, dtype=float)
    out = 0.5 + np.arctan(beta * a) / math.pi
    return float(out) if out.ndim == 0 else out


def normalized_revision_flux(
    z: Array | float, beta: float, *, kernel: str = "fermi"
) -> Array | float:
    """Antisymmetric pair flux normalized to derivative one at the origin."""
    if beta <= 0 or not math.isfinite(beta):
        raise ValueError("beta must be positive and finite")
    a = np.asarray(z, dtype=float)
    if kernel == "fermi":
        out = (2.0 / beta) * np.tanh(0.5 * beta * a)
    elif kernel == "arctan":
        out = np.arctan(beta * a) / beta
    else:
        raise ValueError(f"unknown revision kernel: {kernel}")
    return float(out) if out.ndim == 0 else out


def kernel_event_scale(beta: float, *, kernel: str = "fermi") -> float:
    """Microscopic event-rate multiplier for normalized macroscopic time."""
    if beta <= 0 or not math.isfinite(beta):
        raise ValueError("beta must be positive and finite")
    if kernel == "fermi":
        return 2.0 / beta
    if kernel == "arctan":
        return math.pi / (2.0 * beta)
    raise ValueError(f"unknown revision kernel: {kernel}")


def normalized_flux_second_derivative_sup(beta: float, *, kernel: str = "fermi") -> float:
    """Return ``sup_z |Q_beta''(z)|`` for the normalized comparison flux.

    This is the curvature constant used to separate the finite-sampling
    correction from the deterministic nonlinear-kernel correction.  For
    ``Q_beta(z)=2 tanh(beta*z/2)/beta`` the sharp value is
    ``2 beta/(3 sqrt(3))``.  For ``atan(beta*z)/beta`` it is
    ``9 beta/(8 sqrt(3))``.
    """
    if beta <= 0 or not math.isfinite(beta):
        raise ValueError("beta must be positive and finite")
    if kernel == "fermi":
        return float(2.0 * beta / (3.0 * math.sqrt(3.0)))
    if kernel == "arctan":
        return float(9.0 * beta / (8.0 * math.sqrt(3.0)))
    raise ValueError(f"unknown revision kernel: {kernel}")


@lru_cache(maxsize=None)
def _count_vectors(k: int, m: int) -> tuple[Array, Array]:
    """All multinomial count vectors and their log coefficients."""
    if k < 2 or m < 1:
        raise ValueError("k >= 2 and m >= 1 are required")
    rows: list[tuple[int, ...]] = []

    def rec(prefix: tuple[int, ...], remaining: int, slots: int) -> None:
        if slots == 1:
            rows.append(prefix + (remaining,))
            return
        for value in range(remaining + 1):
            rec(prefix + (value,), remaining - value, slots - 1)

    rec((), m, k)
    counts = np.asarray(rows, dtype=np.int64)
    log_coeff = np.full(len(counts), math.lgamma(m + 1.0), dtype=float)
    for column in range(k):
        log_coeff -= np.vectorize(math.lgamma)(counts[:, column] + 1.0)
    counts.setflags(write=False)
    log_coeff.setflags(write=False)
    return counts, log_coeff


def sample_mean_distribution(
    payoffs: Array,
    x: Array,
    m: int | None,
    *,
    round_decimals: int = 14,
) -> tuple[Array, Array]:
    """Exact distribution of a strategy's sample-mean payoff.

    ``m=None`` denotes full population feedback and returns a point mass.
    Equal support values are compressed after multinomial enumeration.
    """
    x = validate_state(x)
    payoffs = np.asarray(payoffs, dtype=float)
    if payoffs.shape != x.shape:
        raise ValueError("payoff row and state dimension disagree")
    if m is None:
        return np.asarray([float(payoffs @ x)]), np.asarray([1.0])
    if isinstance(m, bool) or int(m) != m or m < 1:
        raise ValueError("m must be a positive integer or None")
    m = int(m)
    counts, log_coeff = _count_vectors(len(x), m)
    log_prob = log_coeff.copy()
    for column, probability in enumerate(x):
        positive = counts[:, column] > 0
        if probability == 0.0:
            log_prob[positive] = -np.inf
        else:
            log_prob += counts[:, column] * math.log(float(probability))
    probabilities = np.exp(log_prob)
    keep = probabilities > 0.0
    means = (counts[keep] @ payoffs) / m
    probabilities = probabilities[keep]
    # Rounding only merges values that are numerically identical sums.
    keys = np.round(means, round_decimals)
    _, inverse = np.unique(keys, return_inverse=True)
    raw_weights = np.bincount(inverse, weights=probabilities)
    weighted_values = np.bincount(inverse, weights=probabilities * means)
    compressed = raw_weights / raw_weights.sum()
    # Preserve moments even if two floating-point representations of the same
    # multinomial sum are merged by the numerical key.
    support = weighted_values / raw_weights
    return support.astype(float), compressed.astype(float)


def one_draw_moments(payoffs: Array, x: Array) -> tuple[float, float, float]:
    """Mean, variance and third central moment of one opponent draw."""
    x = validate_state(x)
    payoffs = np.asarray(payoffs, dtype=float)
    mean = float(payoffs @ x)
    centered = payoffs - mean
    variance = float(x @ (centered**2))
    third = float(x @ (centered**3))
    return mean, max(variance, 0.0), third


def payoff_difference_moments(
    A: Array,
    x: Array,
    i: int,
    j: int,
    m_i: int | None,
    m_j: int | None,
    *,
    sampling_mode: str = "independent",
) -> tuple[float, float, float]:
    """Mean difference and central moments of independent payoff estimates."""
    x = validate_state(x)
    A = validate_game(A, len(x))
    if sampling_mode == "common":
        if m_i != m_j:
            raise ValueError("common sampling requires equal sample sizes")
        mean, variance, third = one_draw_moments(A[i] - A[j], x)
        if m_i is None:
            return mean, 0.0, 0.0
        return mean, variance / m_i, third / (m_i**2)
    if sampling_mode != "independent":
        raise ValueError(f"unknown sampling mode: {sampling_mode}")
    mean_i, var_i, third_i = one_draw_moments(A[i], x)
    mean_j, var_j, third_j = one_draw_moments(A[j], x)
    if m_i is None:
        var_i = third_i = 0.0
    else:
        var_i /= m_i
        third_i /= m_i**2
    if m_j is None:
        var_j = third_j = 0.0
    else:
        var_j /= m_j
        third_j /= m_j**2
    return mean_i - mean_j, var_i + var_j, third_i - third_j


def finite_feedback_pair_deviation_bound(
    A: Array,
    x: Array,
    i: int,
    j: int,
    beta: float,
    m_i: int | None,
    m_j: int | None,
    *,
    kernel: str = "fermi",
    sampling_mode: str = "independent",
) -> float:
    """Bound the finite-sampling correction to one pairwise flux.

    Let ``Z_ij`` be the finite-feedback payoff difference and let
    ``Delta_ij=E[Z_ij]``.  Taylor's theorem gives

    ``|E Q_beta(Z_ij)-Q_beta(Delta_ij)| <= .5 sup|Q_beta''| Var(Z_ij)``.

    The result is exact for the point-mass endpoint ``m_i=m_j=None`` (zero),
    accepts heterogeneous independent sample sizes, and uses the difference
    sample under common sampling.  It is a bound on the *normalized pair
    flux*, before multiplication by ``x_i*x_j``.
    """
    _, variance, _ = payoff_difference_moments(
        A, x, i, j, m_i, m_j, sampling_mode=sampling_mode
    )
    curvature = normalized_flux_second_derivative_sup(beta, kernel=kernel)
    return float(0.5 * curvature * variance)


def finite_feedback_rhs_deviation_bound(
    x: Array,
    A: Array,
    beta: float,
    m: int | None | Iterable[int | None],
    *,
    kernel: str = "fermi",
    sampling_mode: str = "independent",
) -> Array:
    """Componentwise bound for ``|F_E^{m,beta}-F_infty^beta|``.

    The returned nonnegative vector bounds the absolute difference between
    the finite-feedback Exact field and the same bounded-kernel field with
    full payoff feedback.  It is intentionally state-dependent: unlike a
    global payoff-span bound, it records the actual variance induced by the
    current population composition and makes the ``m`` dependence visible.
    """
    x = validate_state(x)
    A = validate_game(A, len(x))
    sample_sizes = normalize_sample_sizes(m, len(x))
    if sampling_mode not in {"independent", "common"}:
        raise ValueError(f"unknown sampling mode: {sampling_mode}")
    if sampling_mode == "common" and len(set(sample_sizes)) != 1:
        raise ValueError("common sampling requires equal sample sizes")
    bounds = np.zeros_like(x)
    for i in range(len(x) - 1):
        for j in range(i + 1, len(x)):
            pair_bound = finite_feedback_pair_deviation_bound(
                A, x, i, j, beta, sample_sizes[i], sample_sizes[j],
                kernel=kernel, sampling_mode=sampling_mode,
            )
            flow_bound = x[i] * x[j] * pair_bound
            bounds[i] += flow_bound
            bounds[j] += flow_bound
    return bounds


def finite_feedback_sample_budget(
    x: Array,
    A: Array,
    beta: float,
    tolerance: float,
    *,
    kernel: str = "fermi",
    sampling_mode: str = "independent",
) -> dict[str, float | int | str]:
    """Return a state-dependent uniform feedback-sample certificate.

    This is the direct inverse of ``finite_feedback_rhs_deviation_bound``.
    For a common uniform sample size ``m`` and i.i.d. sampling, the payoff
    difference variances scale as ``1/m``. Therefore the certified field
    discrepancy is ``C(x,A,beta)/m``. The returned integer is the smallest
    sample size under this bound whose instantaneous vector-field error is no
    larger than the supplied tolerance. It is not an optimal policy and does
    not control trajectories or global stability.
    """
    x = validate_state(x)
    A = validate_game(A, len(x))
    if not math.isfinite(tolerance) or tolerance <= 0.0:
        raise ValueError("tolerance must be positive and finite")
    if sampling_mode not in {"independent", "common"}:
        raise ValueError(f"unknown sampling mode: {sampling_mode}")

    numerator = float(np.linalg.norm(
        finite_feedback_rhs_deviation_bound(
            x, A, beta, 1, kernel=kernel, sampling_mode=sampling_mode,
        ),
        ord=np.inf,
    ))
    sample_size = max(1, int(math.ceil(numerator / tolerance)))
    certified_bound = numerator / sample_size
    while certified_bound > tolerance * (1.0 + 1e-14):
        sample_size += 1
        certified_bound = numerator / sample_size
    return {
        "sample_size": sample_size,
        "certified_bound_inf": float(certified_bound),
        "bound_numerator_m1_inf": numerator,
        "tolerance": float(tolerance),
        "sampling_mode": sampling_mode,
        "kernel": kernel,
    }


def _expected_normalized_flux(
    values_i: Array,
    probabilities_i: Array,
    values_j: Array,
    probabilities_j: Array,
    beta: float,
    kernel: str,
    *,
    chunk_size: int = 1024,
) -> float:
    """Compute the normalized expected pair flux without a huge outer matrix."""
    total = 0.0
    for start in range(0, len(values_i), chunk_size):
        stop = min(start + chunk_size, len(values_i))
        diff = values_i[start:stop, None] - values_j[None, :]
        weights = probabilities_i[start:stop, None] * probabilities_j[None, :]
        total += float(
            np.sum(weights * normalized_revision_flux(diff, beta, kernel=kernel))
        )
    return total


def _difference_raw_moment(
    values_i: Array,
    probabilities_i: Array,
    values_j: Array,
    probabilities_j: Array,
    order: int,
) -> float:
    """Raw moment of two independent discrete variables' difference."""
    total = 0.0
    for power_i in range(order + 1):
        power_j = order - power_i
        moment_i = float(probabilities_i @ (values_i**power_i))
        moment_j = float(probabilities_j @ (values_j**power_j))
        total += (
            math.comb(order, power_i)
            * ((-1.0) ** power_j)
            * moment_i
            * moment_j
        )
    return total


def _one_draw_cumulants(payoffs: Array, x: Array) -> Array:
    """First five cumulants of one categorical payoff draw."""
    payoffs = np.asarray(payoffs, dtype=float)
    x = validate_state(x)
    mean = float(x @ payoffs)
    centered = payoffs - mean
    central2 = float(x @ (centered**2))
    central3 = float(x @ (centered**3))
    central4 = float(x @ (centered**4))
    central5 = float(x @ (centered**5))
    return np.asarray(
        [
            mean,
            central2,
            central3,
            central4 - 3.0 * central2**2,
            central5 - 10.0 * central3 * central2,
        ],
        dtype=float,
    )


def _sample_mean_cumulants(
    payoffs: Array, x: Array, sample_size: int | None
) -> Array:
    cumulants = _one_draw_cumulants(payoffs, x)
    if sample_size is None:
        cumulants[1:] = 0.0
        return cumulants
    for order in range(2, 6):
        cumulants[order - 1] /= sample_size ** (order - 1)
    return cumulants


def _raw_moments_from_cumulants(cumulants: Array) -> Array:
    """Raw moments one through five from cumulants one through five."""
    k1, k2, k3, k4, k5 = np.asarray(cumulants, dtype=float)
    return np.asarray(
        [
            k1,
            k1**2 + k2,
            k1**3 + 3.0 * k1 * k2 + k3,
            k1**4 + 6.0 * k1**2 * k2 + 3.0 * k2**2 + 4.0 * k1 * k3 + k4,
            k1**5
            + 10.0 * k1**3 * k2
            + 15.0 * k1 * k2**2
            + 10.0 * k1**2 * k3
            + 10.0 * k2 * k3
            + 5.0 * k1 * k4
            + k5,
        ],
        dtype=float,
    )


def payoff_difference_raw_moments(
    A: Array,
    x: Array,
    i: int,
    j: int,
    m_i: int | None,
    m_j: int | None,
    *,
    sampling_mode: str = "independent",
) -> Array:
    """Closed-form first five raw moments of sampled payoff difference.

    This uses additivity and scaling of cumulants.  Its cost is independent of
    the multinomial support size, unlike exact distribution enumeration.
    """
    x = validate_state(x)
    A = validate_game(A, len(x))
    if sampling_mode == "common":
        if m_i != m_j:
            raise ValueError("common sampling requires equal sample sizes")
        difference_cumulants = _sample_mean_cumulants(A[i] - A[j], x, m_i)
    elif sampling_mode == "independent":
        left = _sample_mean_cumulants(A[i], x, m_i)
        right = _sample_mean_cumulants(A[j], x, m_j)
        signs = np.asarray([-1.0, 1.0, -1.0, 1.0, -1.0])
        difference_cumulants = left + signs * right
    else:
        raise ValueError(f"unknown sampling mode: {sampling_mode}")
    return _raw_moments_from_cumulants(difference_cumulants)


def classical_rhs(x: Array, A: Array) -> Array:
    x = validate_state(x)
    A = validate_game(A, len(x))
    payoff = A @ x
    return x * (payoff - float(x @ payoff))


def tail_rhs(
    x: Array,
    A: Array,
    beta: float,
    m: int | None | Iterable[int | None],
    *,
    include_skewness: bool,
    kernel: str = "fermi",
    sampling_mode: str = "independent",
) -> Array:
    """Cubic Fermi expansion with optional third feedback moment."""
    x = validate_state(x)
    A = validate_game(A, len(x))
    sample_sizes = normalize_sample_sizes(m, len(x))
    cubic_coefficient = KERNEL_COEFFICIENTS.get(kernel)
    if cubic_coefficient is None:
        raise ValueError(f"unknown revision kernel: {kernel}")
    dx = np.zeros_like(x)
    for i in range(len(x) - 1):
        for j in range(i + 1, len(x)):
            delta, variance, third = payoff_difference_moments(
                A,
                x,
                i,
                j,
                sample_sizes[i],
                sample_sizes[j],
                sampling_mode=sampling_mode,
            )
            cubic_moment = delta**3 + 3.0 * delta * variance
            if include_skewness:
                cubic_moment += third
            normalized_flux = delta - cubic_coefficient[0] * (beta**2) * cubic_moment
            flow = x[i] * x[j] * normalized_flux
            dx[i] += flow
            dx[j] -= flow
    return dx


def exact_rhs(
    x: Array,
    A: Array,
    beta: float,
    m: int | None | Iterable[int | None],
    *,
    kernel: str = "fermi",
    sampling_mode: str = "independent",
) -> Array:
    """Exact normalized mean field for independent finite payoff samples."""
    x = validate_state(x)
    A = validate_game(A, len(x))
    sample_sizes = normalize_sample_sizes(m, len(x))
    if kernel not in KERNEL_COEFFICIENTS:
        raise ValueError(f"unknown revision kernel: {kernel}")
    if sampling_mode not in {"independent", "common"}:
        raise ValueError(f"unknown sampling mode: {sampling_mode}")
    if sampling_mode == "common" and len(set(sample_sizes)) != 1:
        raise ValueError("common sampling requires equal sample sizes")
    distributions = None
    if sampling_mode == "independent":
        distributions = [
            sample_mean_distribution(A[i], x, sample_sizes[i])
            for i in range(len(x))
        ]
    dx = np.zeros_like(x)
    for i in range(len(x) - 1):
        for j in range(i + 1, len(x)):
            if sampling_mode == "independent":
                assert distributions is not None
                values_i, probabilities_i = distributions[i]
                values_j, probabilities_j = distributions[j]
                normalized_flux = _expected_normalized_flux(
                    values_i,
                    probabilities_i,
                    values_j,
                    probabilities_j,
                    beta,
                    kernel,
                )
            else:
                values, probabilities = sample_mean_distribution(
                    A[i] - A[j], x, sample_sizes[i]
                )
                normalized_flux = float(
                    probabilities
                    @ normalized_revision_flux(values, beta, kernel=kernel)
                )
            flow = x[i] * x[j] * normalized_flux
            dx[i] += flow
            dx[j] -= flow
    return dx


def moment_tail_rhs(
    x: Array,
    A: Array,
    beta: float,
    m: int | None | Iterable[int | None],
    *,
    order: int = 3,
    kernel: str = "fermi",
    sampling_mode: str = "independent",
) -> Array:
    """Full raw-moment tail through cubic or fifth order."""
    if order not in {3, 5}:
        raise ValueError("order must be 3 or 5")
    x = validate_state(x)
    A = validate_game(A, len(x))
    sample_sizes = normalize_sample_sizes(m, len(x))
    if sampling_mode not in {"independent", "common"}:
        raise ValueError(f"unknown sampling mode: {sampling_mode}")
    if sampling_mode == "common" and len(set(sample_sizes)) != 1:
        raise ValueError("common sampling requires equal sample sizes")
    coefficients = KERNEL_COEFFICIENTS.get(kernel)
    if coefficients is None:
        raise ValueError(f"unknown revision kernel: {kernel}")
    dx = np.zeros_like(x)
    for i in range(len(x) - 1):
        for j in range(i + 1, len(x)):
            raw_moments = payoff_difference_raw_moments(
                A,
                x,
                i,
                j,
                sample_sizes[i],
                sample_sizes[j],
                sampling_mode=sampling_mode,
            )
            first = float(raw_moments[0])
            third = float(raw_moments[2])
            fifth = float(raw_moments[4]) if order == 5 else 0.0
            normalized_flux = first - coefficients[0] * (beta**2) * third
            if order == 5:
                normalized_flux += coefficients[1] * (beta**4) * fifth
            flow = x[i] * x[j] * normalized_flux
            dx[i] += flow
            dx[j] -= flow
    return dx


def bounded_moment_tail_rhs(
    x: Array,
    A: Array,
    beta: float,
    m: int | None | Iterable[int | None],
    *,
    order: int = 3,
    kernel: str = "fermi",
    sampling_mode: str = "independent",
) -> Array:
    """Structure-preserving moment approximation with physical flux bounds.

    The polynomial moment expansion is projected pairwise onto the admissible
    normalized-flux interval implied by the underlying bounded revision
    kernel.  The projection is inactive in the local weak-feedback regime, so
    the ordinary second/fourth/sixth-order error laws are retained there, but
    it prevents high-order truncations from producing impossible fluxes under
    strong feedback.  The bound is determined by the kernel, never by Exact
    error or a fitted parameter.
    """
    if order not in {3, 5}:
        raise ValueError("order must be 3 or 5")
    x = validate_state(x)
    A = validate_game(A, len(x))
    sample_sizes = normalize_sample_sizes(m, len(x))
    if sampling_mode not in {"independent", "common"}:
        raise ValueError(f"unknown sampling mode: {sampling_mode}")
    if sampling_mode == "common" and len(set(sample_sizes)) != 1:
        raise ValueError("common sampling requires equal sample sizes")
    coefficients = KERNEL_COEFFICIENTS.get(kernel)
    if coefficients is None:
        raise ValueError(f"unknown revision kernel: {kernel}")
    flux_bound = 2.0 / beta if kernel == "fermi" else math.pi / (2.0 * beta)
    dx = np.zeros_like(x)
    for i in range(len(x) - 1):
        for j in range(i + 1, len(x)):
            raw_moments = payoff_difference_raw_moments(
                A,
                x,
                i,
                j,
                sample_sizes[i],
                sample_sizes[j],
                sampling_mode=sampling_mode,
            )
            normalized_flux = float(
                raw_moments[0] - coefficients[0] * (beta**2) * raw_moments[2]
            )
            if order == 5:
                normalized_flux += coefficients[1] * (beta**4) * raw_moments[4]
            normalized_flux = float(np.clip(normalized_flux, -flux_bound, flux_bound))
            flow = x[i] * x[j] * normalized_flux
            dx[i] += flow
            dx[j] -= flow
    return dx


def normalize_sample_sizes(
    m: int | None | Iterable[int | None], k: int
) -> tuple[int | None, ...]:
    if m is None or isinstance(m, (int, np.integer)):
        values = (None if m is None else int(m),) * k
    else:
        values = tuple(m)
        if len(values) != k:
            raise ValueError("sample-size vector has wrong length")
    for value in values:
        if value is not None and (isinstance(value, bool) or int(value) != value or value < 1):
            raise ValueError("sample sizes must be positive integers or None")
    return tuple(None if value is None else int(value) for value in values)


def reduced_tail_c1_bound(
    A: Array,
    beta: float,
    m: int | None | Iterable[int | None],
    *,
    order: int = 3,
    kernel: str = "fermi",
    sampling_mode: str = "independent",
) -> tuple[float, float]:
    """Global reduced-coordinate C0/C1 bounds for an unbounded Taylor tail.

    The return value is ``(epsilon_0, epsilon_1)`` for the standard simplex
    chart ``x=(y, 1-sum(y))``. Here ``epsilon_0`` bounds the infinity norm of
    ``F_exact-F_order`` and ``epsilon_1`` bounds the induced-infinity norm of
    its reduced Jacobian. The calculation implements Lemma 3 in the theory
    draft. It is deliberately conservative, but is closed form and remains
    valid at simplex faces for finite feedback because the multinomial
    expectations are polynomials in ``x``.

    ``order=1`` denotes the classical replicator truncation, while 3 and 5
    denote the corresponding raw-moment Taylor truncations. The bounded
    clipped approximation is excluded: clipping is nonsmooth at its active
    threshold and requires a separate generalized-Jacobian treatment.
    """
    if order not in {1, 3, 5}:
        raise ValueError("order must be 1, 3, or 5")
    A = validate_game(A)
    k = len(A)
    if beta <= 0 or not math.isfinite(beta):
        raise ValueError("beta must be positive and finite")
    if kernel not in KERNEL_COEFFICIENTS:
        raise ValueError(f"unknown revision kernel: {kernel}")
    if sampling_mode not in {"independent", "common"}:
        raise ValueError(f"unknown sampling mode: {sampling_mode}")
    sample_sizes = normalize_sample_sizes(m, k)
    if sampling_mode == "common" and len(set(sample_sizes)) != 1:
        raise ValueError("common sampling requires equal sample sizes")

    payoff_span = float(np.max(A) - np.min(A))
    if order == 1:
        rho0 = ((1.0 / 12.0 if kernel == "fermi" else 1.0 / 3.0)
                * beta**2 * payoff_span**3)
        rho1 = ((1.0 / 4.0 if kernel == "fermi" else 1.0)
                * beta**2 * payoff_span**2)
    elif order == 3:
        rho0 = ((1.0 / 120.0 if kernel == "fermi" else 1.0 / 5.0)
                * beta**4 * payoff_span**5)
        rho1 = ((1.0 / 24.0 if kernel == "fermi" else 1.0)
                * beta**4 * payoff_span**4)
    else:
        rho0 = ((17.0 / 20160.0 if kernel == "fermi" else 1.0 / 7.0)
                * beta**6 * payoff_span**7)
        rho1 = ((17.0 / 2880.0 if kernel == "fermi" else 1.0)
                * beta**6 * payoff_span**6)

    gamma_max = 0.0
    for i in range(k - 1):
        for j in range(i + 1, k):
            if sampling_mode == "independent":
                finite_draws = sum(value for value in (sample_sizes[i], sample_sizes[j])
                                   if value is not None)
                has_deterministic_side = (sample_sizes[i] is None or sample_sizes[j] is None)
            else:
                finite_draws = 0 if sample_sizes[i] is None else sample_sizes[i]
                has_deterministic_side = sample_sizes[i] is None
            gamma = 2.0 * finite_draws * rho0
            if has_deterministic_side:
                gamma += 2.0 * payoff_span * rho1
            gamma_max = max(gamma_max, gamma)

    epsilon0 = rho0 / 4.0
    # In the standard simplex chart the induced-infinity norm is a row sum.
    # The prefactor derivatives contribute at most 2*k-3 per reduced row;
    # the pair-residual derivative term is accumulated across k-1 columns.
    epsilon1 = (2 * k - 3) * rho0 + (k - 1) * gamma_max / 4.0
    return float(epsilon0), float(epsilon1)


def rk4_integrate(
    rhs: Callable[[Array], Array],
    x0: Array,
    horizon: float,
    record_dt: float,
    *,
    internal_dt: float = 0.0025,
) -> tuple[Array, Array]:
    x = validate_state(x0).copy()
    if horizon <= 0 or record_dt <= 0 or internal_dt <= 0:
        raise ValueError("time arguments must be positive")
    rows = int(round(horizon / record_dt)) + 1
    times = np.linspace(0.0, horizon, rows)
    trajectory = np.empty((rows, len(x)))
    trajectory[0] = x
    for row in range(1, rows):
        remaining = float(times[row] - times[row - 1])
        while remaining > 1e-14:
            h = min(internal_dt, remaining)
            k1 = rhs(x)
            k2 = rhs(x + 0.5 * h * k1)
            k3 = rhs(x + 0.5 * h * k2)
            k4 = rhs(x + h * k3)
            proposal = x + (h / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)
            if np.min(proposal) < -1e-9:
                raise FloatingPointError("ODE step left the simplex")
            x = np.maximum(proposal, 0.0)
            x /= x.sum()
            remaining -= h
        trajectory[row] = x
    return times, trajectory


def empirical_local_rhs(
    x: Array,
    A: Array,
    beta: float,
    m: int | None | Iterable[int | None],
    samples_per_pair: int,
    seed: int,
    *,
    kernel: str = "fermi",
    sampling_mode: str = "independent",
) -> tuple[Array, Array]:
    """Monte Carlo estimate of conditional drift using actual switch draws.

    Returns the drift estimate and a conservative component-wise standard
    error obtained by adding independent pair variances.
    """
    x = validate_state(x)
    A = validate_game(A, len(x))
    if samples_per_pair < 2:
        raise ValueError("samples_per_pair must be at least two")
    sample_sizes = normalize_sample_sizes(m, len(x))
    if kernel not in KERNEL_COEFFICIENTS:
        raise ValueError(f"unknown revision kernel: {kernel}")
    if sampling_mode not in {"independent", "common"}:
        raise ValueError(f"unknown sampling mode: {sampling_mode}")
    if sampling_mode == "common" and len(set(sample_sizes)) != 1:
        raise ValueError("common sampling requires equal sample sizes")
    rng = np.random.default_rng(seed)
    estimate = np.zeros_like(x)
    component_variance = np.zeros_like(x)
    for i in range(len(x) - 1):
        for j in range(i + 1, len(x)):
            if sampling_mode == "common":
                common_m = sample_sizes[i]
                if common_m is None:
                    difference = np.full(
                        samples_per_pair, float((A[i] - A[j]) @ x)
                    )
                else:
                    common_counts = rng.multinomial(
                        common_m, x, size=samples_per_pair
                    )
                    difference = (common_counts @ (A[i] - A[j])) / common_m
            else:
                if sample_sizes[i] is None:
                    payoff_i = np.full(samples_per_pair, float(A[i] @ x))
                else:
                    counts_i = rng.multinomial(
                        sample_sizes[i], x, size=samples_per_pair
                    )
                    payoff_i = (counts_i @ A[i]) / sample_sizes[i]
                if sample_sizes[j] is None:
                    payoff_j = np.full(samples_per_pair, float(A[j] @ x))
                else:
                    counts_j = rng.multinomial(
                        sample_sizes[j], x, size=samples_per_pair
                    )
                    payoff_j = (counts_j @ A[j]) / sample_sizes[j]
                difference = payoff_i - payoff_j
            forward = rng.random(samples_per_pair) < revision_probability(
                difference, beta, kernel=kernel
            )
            reverse = rng.random(samples_per_pair) < revision_probability(
                -difference, beta, kernel=kernel
            )
            normalized = kernel_event_scale(beta, kernel=kernel) * (
                forward.astype(float) - reverse.astype(float)
            )
            q_hat = float(normalized.mean())
            q_variance = float(normalized.var(ddof=1) / samples_per_pair)
            weight = x[i] * x[j]
            flow = weight * q_hat
            estimate[i] += flow
            estimate[j] -= flow
            component_variance[i] += weight**2 * q_variance
            component_variance[j] += weight**2 * q_variance
    return estimate, np.sqrt(component_variance)


def initial_counts(x0: Array, population: int) -> Array:
    x0 = validate_state(x0)
    if population < len(x0):
        raise ValueError("population is too small")
    raw = population * x0
    counts = np.floor(raw).astype(int)
    remainder = population - int(counts.sum())
    order = np.argsort(-(raw - counts))
    counts[order[:remainder]] += 1
    return counts


def finite_population_generator_rhs(
    counts: Array,
    A: Array,
    beta: float,
    m: int | None | Iterable[int | None],
    *,
    kernel: str = "fermi",
    sampling_mode: str = "independent",
) -> Array:
    """Exact drift of the finite-N pairwise-revision chain.

    This is the generator associated with :func:`agent_trajectory` for
    sampling with replacement. It keeps focal/model self-exclusion and the
    without-self ordered-pair probability, so its convergence to the infinite
    population exact mean field can be checked without Monte Carlo noise.
    """
    counts = np.asarray(counts, dtype=np.int64)
    if counts.ndim != 1 or np.any(counts < 0):
        raise ValueError("counts must be a non-negative one-dimensional array")
    population = int(counts.sum())
    if population < 3:
        raise ValueError("population must be at least three")
    A = validate_game(A, len(counts))
    sample_sizes = normalize_sample_sizes(m, len(counts))
    if kernel not in KERNEL_COEFFICIENTS:
        raise ValueError(f"unknown revision kernel: {kernel}")
    if sampling_mode not in {"independent", "common"}:
        raise ValueError(f"unknown sampling mode: {sampling_mode}")
    if sampling_mode == "common" and len(set(sample_sizes)) != 1:
        raise ValueError("common sampling requires equal sample sizes")
    x = counts / population
    dx = np.zeros(len(counts), dtype=float)
    for i in range(len(counts) - 1):
        for j in range(i + 1, len(counts)):
            if counts[i] == 0 or counts[j] == 0:
                continue
            if sampling_mode == "independent":
                pool_i = counts.copy(); pool_i[i] -= 1
                pool_j = counts.copy(); pool_j[j] -= 1
                values_i, probabilities_i = sample_mean_distribution(
                    A[i], pool_i / (population - 1), sample_sizes[i]
                )
                values_j, probabilities_j = sample_mean_distribution(
                    A[j], pool_j / (population - 1), sample_sizes[j]
                )
                normalized_flux = _expected_normalized_flux(
                    values_i, probabilities_i, values_j, probabilities_j,
                    beta, kernel,
                )
            else:
                pool = counts.copy(); pool[i] -= 1; pool[j] -= 1
                values, probabilities = sample_mean_distribution(
                    A[i] - A[j], pool / (population - 2), sample_sizes[i]
                )
                normalized_flux = float(
                    probabilities @ normalized_revision_flux(values, beta, kernel=kernel)
                )
            ordered_pair_correction = population / (population - 1)
            flow = ordered_pair_correction * x[i] * x[j] * normalized_flux
            dx[i] += flow
            dx[j] -= flow
    return dx


def _sample_payoff_from_pool(
    payoff_row: Array,
    pool_counts: Array,
    sample_size: int | None,
    rng: np.random.Generator,
    *,
    replacement: bool,
) -> float:
    """Sample a payoff from an explicitly specified eligible-opponent pool."""
    pool_counts = np.asarray(pool_counts, dtype=np.int64)
    pool_size = int(pool_counts.sum())
    if pool_size < 1 or np.any(pool_counts < 0):
        raise ValueError("eligible opponent pool is empty or invalid")
    probabilities = pool_counts / pool_size
    if sample_size is None:
        return float(np.asarray(payoff_row, dtype=float) @ probabilities)
    if not replacement and sample_size > pool_size:
        raise ValueError("sample size exceeds opponent pool without replacement")
    if replacement:
        if sample_size == 1:
            draw = int(rng.integers(pool_size))
            strategy = int(np.searchsorted(np.cumsum(pool_counts), draw, side="right"))
            return float(payoff_row[strategy])
        sampled_counts = rng.multinomial(sample_size, probabilities)
    else:
        sampled_counts = rng.multivariate_hypergeometric(pool_counts, sample_size)
    return float(sampled_counts @ payoff_row) / sample_size


def agent_trajectory(
    A: Array,
    x0: Array,
    population: int,
    horizon: float,
    record_dt: float,
    beta: float,
    m: int | None | Iterable[int | None],
    seed: int,
    *,
    kernel: str = "fermi",
    sampling_mode: str = "independent",
    replacement: bool = True,
) -> tuple[Array, Array]:
    """Finite-population revision with self-excluded payoff sampling.

    Independent feedback lets each compared player sample from the population
    excluding itself. Common feedback uses the same sampled opponents for
    both players and excludes both members of the comparison pair. Sampling
    with replacement is the main specification because it converges directly
    to the i.i.d. exact mean field; without-replacement sampling is available
    as a finite-population robustness check.
    """
    x0 = validate_state(x0)
    A = validate_game(A, len(x0))
    sample_sizes = normalize_sample_sizes(m, len(x0))
    if kernel not in KERNEL_COEFFICIENTS:
        raise ValueError(f"unknown revision kernel: {kernel}")
    if sampling_mode not in {"independent", "common"}:
        raise ValueError(f"unknown sampling mode: {sampling_mode}")
    if sampling_mode == "common" and len(set(sample_sizes)) != 1:
        raise ValueError("common sampling requires equal sample sizes")
    rng = np.random.default_rng(seed)
    counts = initial_counts(x0, population)
    strategies = np.repeat(np.arange(len(x0)), counts)
    rng.shuffle(strategies)
    rows = int(round(horizon / record_dt)) + 1
    times = np.linspace(0.0, horizon, rows)
    trajectory = np.empty((rows, len(x0)))
    trajectory[0] = counts / population
    event_scale = kernel_event_scale(beta, kernel=kernel)
    total_events = int(round(horizon * population * event_scale))
    targets = np.rint(times[1:] * population * event_scale).astype(int)
    next_row = 1
    for event in range(1, total_events + 1):
        focal_index = int(rng.integers(population))
        model_index = int(rng.integers(population - 1))
        model_index += model_index >= focal_index
        old = int(strategies[focal_index])
        candidate = int(strategies[model_index])
        if old != candidate:
            if sampling_mode == "common":
                pool = counts.copy()
                pool[old] -= 1
                pool[candidate] -= 1
                common_m = sample_sizes[old]
                if common_m is None:
                    probabilities = pool / int(pool.sum())
                    payoff_old = float(A[old] @ probabilities)
                    payoff_candidate = float(A[candidate] @ probabilities)
                else:
                    pool_size = int(pool.sum())
                    if not replacement and common_m > pool_size:
                        raise ValueError(
                            "sample size exceeds common opponent pool without replacement"
                        )
                    probabilities = pool / pool_size
                    if replacement:
                        if common_m == 1:
                            draw = int(rng.integers(pool_size))
                            strategy = int(np.searchsorted(np.cumsum(pool), draw, side="right"))
                            payoff_old = float(A[old, strategy])
                            payoff_candidate = float(A[candidate, strategy])
                            sampled = None
                        else:
                            sampled = rng.multinomial(common_m, probabilities)
                    else:
                        sampled = rng.multivariate_hypergeometric(pool, common_m)
                    if sampled is not None:
                        payoff_old = float(sampled @ A[old]) / common_m
                        payoff_candidate = float(sampled @ A[candidate]) / common_m
            else:
                old_pool = counts.copy()
                old_pool[old] -= 1
                candidate_pool = counts.copy()
                candidate_pool[candidate] -= 1
                payoff_old = _sample_payoff_from_pool(
                    A[old], old_pool, sample_sizes[old], rng,
                    replacement=replacement,
                )
                payoff_candidate = _sample_payoff_from_pool(
                    A[candidate], candidate_pool, sample_sizes[candidate], rng,
                    replacement=replacement,
                )
            if rng.random() < revision_probability(
                payoff_candidate - payoff_old, beta, kernel=kernel
            ):
                strategies[focal_index] = candidate
                counts[old] -= 1
                counts[candidate] += 1
        while next_row < rows and event >= targets[next_row - 1]:
            trajectory[next_row] = counts / population
            next_row += 1
    if next_row < rows:
        trajectory[next_row:] = counts / population
    return times, trajectory
